import type {
  Team,
  Round,
  SubmissionRound1,
  SubmissionRound2,
  Round3Duel,
  Round3Submission,
  MissionTask,
  AIJob,
  Round2Prompt,
  Round3Question,
} from "./models";

const now = new Date();
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60_000);

export const SEED_TEAMS: Team[] = [];

export const SEED_ROUNDS: Round[] = [
  {
    id: "round1",
    name: "Algorithm Challenge",
    status: "active",
    startTime: minutesAgo(240),
  },
  {
    id: "round2",
    name: "Capture the Hostile",
    status: "active",
    startTime: minutesAgo(60),
  },
  {
    id: "round3",
    name: "1v1 Face-Off",
    status: "pending",
  },
];

export const SEED_ROUND2_PROMPTS: Round2Prompt[] = [
  {
    id: "ts-1",
    title: "Missing null guard",
    language: "TypeScript",
    difficulty: "easy",
    snippet: `function getDisplayName(user?: { profile?: { name?: string } }) {\n  return user.profile.name.toUpperCase();\n}`,
    context: "Ensure defensive coding when optional fields are accessed.",
    tags: ["null-check", "defensive"],
    answer: {
      summary: "Accessing profile.name without verifying user/profile/name is defined.",
      keywords: ["profile", "name", "undefined"],
      line: 2,
      tolerance: 0,
      partialCreditLines: [1, 3],
    },
  },
  {
    id: "ts-2",
    title: "Async forEach escape",
    language: "TypeScript",
    difficulty: "medium",
    snippet: `async function loadUsers(ids: string[]) {\n  const users: User[] = [];\n  ids.forEach(async (id) => {\n    const user = await fetchUser(id);\n    users.push(user);\n  });\n  return users;\n}`,
    context: "Reveal async control flow bugs when iterating collections.",
    tags: ["async", "foreach", "typescript"],
    answer: {
      summary: "Using forEach with async ignores awaited work so loadUsers resolves before fetchUser completes.",
      keywords: ["forEach", "async", "await"],
      line: 3,
      tolerance: 0,
      partialCreditLines: [4, 5],
    },
  },
  {
    id: "ts-3",
    title: "Reduce without seed",
    language: "TypeScript",
    difficulty: "easy",
    snippet: `function average(scores: number[]) {\n  const total = scores.reduce((sum, value) => sum + value);\n  return total / scores.length;\n}`,
    context: "Handle collection reducers that also accept empty arrays.",
    tags: ["reduce", "typescript"],
    answer: {
      summary: "Calling reduce without an initial value throws when scores is empty.",
      keywords: ["reduce", "initial", "empty"],
      line: 2,
      tolerance: 0,
      partialCreditLines: [1, 3],
    },
  },
  {
    id: "ts-4",
    title: "Falsy timeout fallback",
    language: "TypeScript",
    difficulty: "medium",
    snippet: `function applyTimeout(options: { timeout?: number }) {\n  const timeout = options.timeout || 1000;\n  return timeout;\n}`,
    context: "Guard configuration defaults that accept 0 as a valid value.",
    tags: ["config", "defaults"],
    answer: {
      summary: "Using || treats 0 as falsy, preventing callers from requesting a zero-millisecond timeout.",
      keywords: ["timeout", "||", "zero"],
      line: 2,
      tolerance: 0,
      partialCreditLines: [1, 3],
    },
  },
  {
    id: "ts-5",
    title: "Map bracket mutation",
    language: "TypeScript",
    difficulty: "medium",
    snippet: `const cache = new Map<string, number>();\n\nfunction setScore(id: string, score: number) {\n  cache[id] = score;\n}`,
    context: "Differentiate Map APIs from plain object access.",
    tags: ["map", "collections"],
    answer: {
      summary: "Assigning with cache[id] writes to the object wrapper instead of the Map entry; use set().",
      keywords: ["Map", "bracket", "set"],
      line: 4,
      tolerance: 0,
    },
  },
  {
    id: "ts-6",
    title: "Missing await on json",
    language: "TypeScript",
    difficulty: "medium",
    snippet: 'async function getProfile(id: string) {\n  const response = await fetch(`/api/users/${id}`);\n  const data = response.json();\n  return data.profile;\n}',
    context: "Catch promise-returning helpers that still need awaiting.",
    tags: ["fetch", "async"],
    answer: {
      summary: "response.json() returns a promise; without await, data.profile is undefined.",
      keywords: ["json", "await", "promise"],
      line: 3,
      tolerance: 0,
    },
  },
  {
    id: "ts-7",
    title: "Truthiness leak",
    language: "TypeScript",
    difficulty: "easy",
    snippet: `function isReady(status: "ready" | "pending") {\n  return status === "ready" || "pending";\n}`,
    context: "Highlight logic errors introduced by truthy short-circuit checks.",
    tags: ["logic", "typescript"],
    answer: {
      summary: "The expression returns the string 'pending', so isReady is always truthy.",
      keywords: ["truthy", "||", "pending"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "ts-8",
    title: "Optional toFixed crash",
    language: "TypeScript",
    difficulty: "easy",
    snippet: `function formatPrice(value?: number) {\n  return "$" + value.toFixed(2);\n}`,
    context: "Protect optional inputs before using number-only APIs.",
    tags: ["optional", "formatting"],
    answer: {
      summary: "value can be undefined, so calling toFixed throws a TypeError.",
      keywords: ["toFixed", "undefined", "optional"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "ts-9",
    title: "Unawaited promise list",
    language: "TypeScript",
    difficulty: "medium",
    snippet: `async function saveAll(ids: string[]) {\n  return ids.map(async (id) => save(id));\n}`,
    context: "Expose collection helpers that return promises without coordination.",
    tags: ["promises", "async"],
    answer: {
      summary: "Returning the map of promises leaves callers with unresolved work; wrap with await Promise.all.",
      keywords: ["Promise.all", "map", "async"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "ts-10",
    title: "Mutable merge",
    language: "TypeScript",
    difficulty: "medium",
    snippet: `function mergeSettings(defaults: Record<string, unknown>, overrides: Record<string, unknown>) {\n  return Object.assign(defaults, overrides);\n}`,
    context: "Spot situations where reference configuration objects get mutated.",
    tags: ["Object.assign", "mutation"],
    answer: {
      summary: "Object.assign writes into defaults, so callers lose the original baseline object.",
      keywords: ["Object.assign", "mutate", "defaults"],
      line: 2,
      tolerance: 0,
      partialCreditLines: [1, 3],
    },
  },
  {
    id: "py-1",
    title: "Default list trap",
    language: "Python",
    difficulty: "medium",
    snippet: `def accumulate(values, acc=[]):\n    for value in values:\n        acc.append(value)\n    return acc`,
    context: "Investigate hidden state bugs in default arguments.",
    tags: ["defaults", "mutable"],
    answer: {
      summary: "Default mutable argument acc persists between calls.",
      keywords: ["default", "mutable", "list"],
      line: 1,
      tolerance: 0,
    },
  },
  {
    id: "py-2",
    title: "String identity check",
    language: "Python",
    difficulty: "easy",
    snippet: `def is_admin(role):\n    return role is "admin"`,
    context: "Differentiate identity from equality when comparing strings.",
    tags: ["strings", "identity"],
    answer: {
      summary: "Using is relies on object identity; use == for string comparison.",
      keywords: ["is", "==", "string"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "py-3",
    title: "Unclosed file handle",
    language: "Python",
    difficulty: "medium",
    snippet: `def read_config(path):\n    file = open(path)\n    content = file.read()\n    return content`,
    context: "Prefer context managers when working with file descriptors.",
    tags: ["io", "files"],
    answer: {
      summary: "open(path) is used without a context manager, leaving the file handle unclosed.",
      keywords: ["open", "close", "contextmanager"],
      line: 2,
      tolerance: 0,
      partialCreditLines: [3],
    },
  },
  {
    id: "py-4",
    title: "Average zero division",
    language: "Python",
    difficulty: "easy",
    snippet: `def average(values):\n    return sum(values) / len(values)`,
    context: "Handle empty collections before performing division.",
    tags: ["math", "division"],
    answer: {
      summary: "len(values) can be zero, causing a ZeroDivisionError.",
      keywords: ["division", "zero", "len"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "py-5",
    title: "Lambda late binding",
    language: "Python",
    difficulty: "medium",
    snippet: `def build_runners(items):\n    callbacks = []\n    for item in items:\n        callbacks.append(lambda: process(item))\n    return callbacks`,
    context: "Showcase closure capture issues inside loops.",
    tags: ["lambda", "closures"],
    answer: {
      summary: "The lambda captures item by reference, so every callback processes the last value.",
      keywords: ["lambda", "closure", "late binding"],
      line: 4,
      tolerance: 0,
      partialCreditLines: [3],
    },
  },
  {
    id: "py-6",
    title: "Sort return confusion",
    language: "Python",
    difficulty: "easy",
    snippet: `def sort_items(items):\n    return items.sort()`,
    context: "Remember which list helpers mutate in-place versus return values.",
    tags: ["lists", "mutation"],
    answer: {
      summary: "list.sort mutates in place and returns None, so callers get None instead of a list.",
      keywords: ["sort", "None", "list"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "py-7",
    title: "Frozen timestamp default",
    language: "Python",
    difficulty: "medium",
    snippet: `from datetime import datetime\n\ndef schedule_event(run_at=datetime.now()):\n    return run_at`,
    context: "Understand that default arguments execute at definition time.",
    tags: ["datetime", "defaults"],
    answer: {
      summary: "datetime.now() runs once at import, so every call reuses the same timestamp.",
      keywords: ["datetime.now", "default", "import"],
      line: 3,
      tolerance: 0,
    },
  },
  {
    id: "py-8",
    title: "Default set reuse",
    language: "Python",
    difficulty: "medium",
    snippet: `def append_unique(value, collection=set()):\n    collection.add(value)\n    return collection`,
    context: "Spot mutable default arguments on sets as well as lists.",
    tags: ["defaults", "set"],
    answer: {
      summary: "collection=set() shares the same set across calls, leaking state between invocations.",
      keywords: ["default", "set", "shared"],
      line: 1,
      tolerance: 0,
    },
  },
  {
    id: "py-9",
    title: "Removal while iterating",
    language: "Python",
    difficulty: "medium",
    snippet: `def remove_all(values, target):\n    for value in values:\n        if value == target:\n            values.remove(value)`,
    context: "Highlight iterator invalidation when mutating a list mid-loop.",
    tags: ["lists", "iteration"],
    answer: {
      summary: "Removing elements from values while iterating skips consecutive matches.",
      keywords: ["remove", "iteration", "skip"],
      line: 4,
      tolerance: 0,
      partialCreditLines: [3],
    },
  },
  {
    id: "py-10",
    title: "Append return value",
    language: "Python",
    difficulty: "easy",
    snippet: `def add_item(items, item):\n    return items.append(item)`,
    context: "Recall which list helpers mutate and what they return.",
    tags: ["lists", "api"],
    answer: {
      summary: "list.append returns None so add_item always returns None instead of the list.",
      keywords: ["append", "None", "list"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "java-1",
    title: "Integer division trap",
    language: "Java",
    difficulty: "easy",
    snippet: `int percentage = count / total * 100;\nSystem.out.println(percentage + "%");`,
    context: "Spot arithmetic precision losses.",
    tags: ["math", "precision"],
    answer: {
      summary: "Integer division truncates before multiplying so the percentage is inaccurate.",
      keywords: ["integer", "division", "precision"],
      line: 1,
      tolerance: 0,
    },
  },
  {
    id: "java-2",
    title: "String identity check",
    language: "Java",
    difficulty: "easy",
    snippet: `if (status == "READY") {\n    trigger();\n}`,
    context: "Enforce equals() when comparing Java strings.",
    tags: ["strings", "comparison"],
    answer: {
      summary: "Using == compares references; equals() should be used for string content.",
      keywords: ["==", "equals", "String"],
      line: 1,
      tolerance: 0,
    },
  },
  {
    id: "java-3",
    title: "Loop bounds overflow",
    language: "Java",
    difficulty: "medium",
    snippet: `for (int i = 0; i <= items.size(); i++) {\n    System.out.println(items.get(i));\n}`,
    context: "Validate loop termination conditions on collections.",
    tags: ["loops", "bounds"],
    answer: {
      summary: "Using <= allows i to equal size(), causing IndexOutOfBoundsException on the last iteration.",
      keywords: ["<=", "IndexOutOfBounds", "loop"],
      line: 1,
      tolerance: 0,
    },
  },
  {
    id: "java-4",
    title: "Leaking FileInputStream",
    language: "Java",
    difficulty: "medium",
    snippet: `FileInputStream stream = new FileInputStream(path);\nString content = new String(stream.readAllBytes());\nreturn content;`,
    context: "Require try-with-resources for IO operations.",
    tags: ["io", "resources"],
    answer: {
      summary: "The FileInputStream is never closed; wrap it in try-with-resources.",
      keywords: ["FileInputStream", "close", "resource leak"],
      line: 1,
      tolerance: 0,
      partialCreditLines: [2],
    },
  },
  {
    id: "java-5",
    title: "Arrays.asList mutation",
    language: "Java",
    difficulty: "medium",
    snippet: `List<String> names = Arrays.asList("sam", "jill");\nnames.add("li");`,
    context: "Remember that Arrays.asList returns a fixed-size view.",
    tags: ["collections", "arrays"],
    answer: {
      summary: "The list returned by Arrays.asList cannot change size; add throws UnsupportedOperationException.",
      keywords: ["Arrays.asList", "add", "UnsupportedOperation"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "java-6",
    title: "Unchecked Optional",
    language: "Java",
    difficulty: "medium",
    snippet: `Optional<User> user = findUser(id);\nreturn user.get();`,
    context: "Encourage presence checks before dereferencing Optional.",
    tags: ["optional", "null"],
    answer: {
      summary: "Calling get() without checking isPresent() can throw NoSuchElementException.",
      keywords: ["Optional", "get", "NoSuchElement"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "java-7",
    title: "Remove during iteration",
    language: "Java",
    difficulty: "medium",
    snippet: `for (String item : items) {\n    if (item.equals(target)) {\n        items.remove(item);\n    }\n}`,
    context: "Expose concurrent modification issues when altering lists mid-iteration.",
    tags: ["collections", "iteration"],
    answer: {
      summary: "Removing from items inside the enhanced for loop triggers ConcurrentModificationException.",
      keywords: ["remove", "ConcurrentModification", "iterator"],
      line: 3,
      tolerance: 0,
      partialCreditLines: [2],
    },
  },
  {
    id: "java-8",
    title: "Unchecked map value",
    language: "Java",
    difficulty: "easy",
    snippet: `String value = map.get(key);\nreturn value.toUpperCase();`,
    context: "Defend against null returns from Map#get.",
    tags: ["null", "collections"],
    answer: {
      summary: "map.get(key) can return null; calling toUpperCase() would throw NullPointerException.",
      keywords: ["map", "null", "toUpperCase"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "java-9",
    title: "Month off by one",
    language: "Java",
    difficulty: "medium",
    snippet: `Date launch = new Date(2025, 10, 1);`,
    context: "Remember legacy Date months are zero-based.",
    tags: ["dates", "off-by-one"],
    answer: {
      summary: "The Date constructor treats months as zero-based, so month 10 represents November instead of October.",
      keywords: ["Date", "month", "zero-based"],
      line: 1,
      tolerance: 0,
    },
  },
  {
    id: "java-10",
    title: "Regex dot split",
    language: "Java",
    difficulty: "medium",
    snippet: `String[] parts = input.split(".");`,
    context: "Clarify that split() receives a regular expression.",
    tags: ["regex", "strings"],
    answer: {
      summary: 'The dot in regex matches any character; split(".") consumes everything instead of literal periods.',
      keywords: ["split", "regex", "dot"],
      line: 1,
      tolerance: 0,
      partialCreditLines: [2],
    },
  },
  {
    id: "cpp-1",
    title: "Dangling reference",
    language: "C++",
    difficulty: "medium",
    snippet: `const std::string& makeGreeting() {\n    std::string name = "Agent";\n    return name;\n}`,
    context: "Avoid returning references to local stack objects.",
    tags: ["lifetime", "references"],
    answer: {
      summary: "Returns reference to local string that is destroyed after function exits.",
      keywords: ["reference", "local", "lifetime"],
      line: 3,
      tolerance: 0,
      partialCreditLines: [2],
    },
  },
  {
    id: "cpp-2",
    title: "Missing virtual destructor",
    language: "C++",
    difficulty: "hard",
    snippet: `struct Base {\n    ~Base() {}\n};\nstruct Derived : Base {\n    ~Derived() { cleanup(); }\n};\n\nvoid release(Base* ptr) {\n    delete ptr;\n}`,
    context: "Require polymorphic bases to declare virtual destructors.",
    tags: ["virtual", "destructor"],
    answer: {
      summary: "Deleting Derived via Base pointer without virtual destructor skips Derived cleanup.",
      keywords: ["delete", "virtual", "destructor"],
      line: 1,
      tolerance: 0,
      partialCreditLines: [4, 7],
    },
  },
  {
    id: "cpp-3",
    title: "Iterator invalidation",
    language: "C++",
    difficulty: "medium",
    snippet: `std::vector<int> values = {1, 2, 3, 4};\nfor (auto it = values.begin(); it != values.end(); ++it) {\n    if (*it % 2 == 0) {\n        values.erase(it);\n    }\n}`,
    context: "Understand that erase invalidates iterators mid-loop.",
    tags: ["iterators", "erase"],
    answer: {
      summary: "Erasing with iterator inside loop invalidates current iterator before increment.",
      keywords: ["erase", "iterator", "invalidate"],
      line: 4,
      tolerance: 0,
      partialCreditLines: [3],
    },
  },
  {
    id: "cpp-4",
    title: "Signed/unsigned clash",
    language: "C++",
    difficulty: "medium",
    snippet: `int remaining = -1;\nfor (size_t i = 0; i < remaining; ++i) {\n    process();\n}`,
    context: "Call out subtle underflow when comparing signed and unsigned types.",
    tags: ["unsigned", "comparison"],
    answer: {
      summary: "remaining is negative so it converts to large size_t, causing loop to run unexpectedly.",
      keywords: ["size_t", "conversion", "loop"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "cpp-5",
    title: "Memory leak",
    language: "C++",
    difficulty: "easy",
    snippet: `void allocate() {\n    int* data = new int[256];\n    compute(data);\n}`,
    context: "Remember to free heap memory.",
    tags: ["memory", "leak"],
    answer: {
      summary: "new allocation is never deleted leading to leak.",
      keywords: ["new", "delete", "leak"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "cpp-6",
    title: "Move misuse",
    language: "C++",
    difficulty: "medium",
    snippet: `std::string source = "data";\nconst std::string& keep = source;\nstd::string target = std::move(source);\nuse(keep);`,
    context: "Beware dangling references after std::move.",
    tags: ["move", "references"],
    answer: {
      summary: "keep references moved-from string leaving it in unspecified state when later used.",
      keywords: ["std::move", "reference", "moved-from"],
      line: 4,
      tolerance: 0,
      partialCreditLines: [2, 3],
    },
  },
  {
    id: "cpp-7",
    title: "Out-of-range indexing",
    language: "C++",
    difficulty: "easy",
    snippet: `std::vector<int> data = {1,2,3};\nfor (size_t i = 0; i <= data.size(); ++i) {\n    sum += data[i];\n}`,
    context: "Avoid <= when iterating vector indices.",
    tags: ["loops", "bounds"],
    answer: {
      summary: "Loop allows i == size() causing out-of-bounds access on last iteration.",
      keywords: ["<=", "vector", "bounds"],
      line: 3,
      tolerance: 0,
    },
  },
  {
    id: "cpp-8",
    title: "Uninitialized member",
    language: "C++",
    difficulty: "medium",
    snippet: `struct Point {\n    Point() {}\n    int x;\n    int y;\n};\n\nPoint p;\nprint(p.x + p.y);`,
    context: "Highlight members left uninitialized in default constructor.",
    tags: ["constructors", "initialization"],
    answer: {
      summary: "Default constructor leaves x and y uninitialized before use.",
      keywords: ["constructor", "uninitialized", "members"],
      line: 2,
      tolerance: 0,
      partialCreditLines: [6],
    },
  },
  {
    id: "cpp-9",
    title: "Missing override",
    language: "C++",
    difficulty: "medium",
    snippet: `struct Base { virtual void run(); };\nstruct Derived : Base {\n    void run(int mode);\n};\n\nvoid execute(Base* ptr) {\n    ptr->run();\n}`,
    context: "Ensure overrides match base signatures.",
    tags: ["override", "polymorphism"],
    answer: {
      summary: "Derived defines overload instead of overriding run(), so Base::run executes.",
      keywords: ["override", "signature", "virtual"],
      line: 3,
      tolerance: 0,
    },
  },
  {
    id: "cpp-10",
    title: "std::string_view lifetime",
    language: "C++",
    difficulty: "hard",
    snippet: `std::string_view idFromBuffer() {\n    std::string buffer = read();\n    return std::string_view(buffer);\n}`,
    context: "Watch for dangling string_view referencing temporary storage.",
    tags: ["string_view", "lifetime"],
    answer: {
      summary: "string_view references buffer that is destroyed when function returns.",
      keywords: ["string_view", "lifetime", "dangling"],
      line: 3,
      tolerance: 0,
      partialCreditLines: [2],
    },
  },
  {
    id: "c-1",
    title: "Missing terminator",
    language: "C",
    difficulty: "medium",
    snippet: `char buffer[8];\nstrncpy(buffer, input, sizeof(buffer));\nprintf("%s\n", buffer);`,
    context: "Remember to null-terminate after strncpy.",
    tags: ["strings", "strncpy"],
    answer: {
      summary: "strncpy does not guarantee null terminator when input length >= buffer size.",
      keywords: ["strncpy", "null", "terminator"],
      line: 2,
      tolerance: 0,
      partialCreditLines: [1],
    },
  },
  {
    id: "c-2",
    title: "Double free",
    language: "C",
    difficulty: "hard",
    snippet: `void release(char* data) {\n    free(data);\n    free(data);\n}`,
    context: "Prevent freeing the same pointer twice.",
    tags: ["memory", "free"],
    answer: {
      summary: "Pointer is freed twice leading to undefined behavior.",
      keywords: ["free", "double", "undefined"],
      line: 3,
      tolerance: 0,
    },
  },
  {
    id: "c-3",
    title: "Stack array overflow",
    language: "C",
    difficulty: "medium",
    snippet: `int values[4];\nfor (int i = 0; i <= 4; ++i) {\n    values[i] = i;\n}`,
    context: "Avoid writing past fixed-size arrays.",
    tags: ["arrays", "bounds"],
    answer: {
      summary: "Loop writes to values[4], which is out of bounds.",
      keywords: ["array", "overflow", "bounds"],
      line: 3,
      tolerance: 0,
    },
  },
  {
    id: "c-4",
    title: "Uninitialized pointer",
    language: "C",
    difficulty: "medium",
    snippet: `char* name;\nprintf("%s\n", name);`,
    context: "Initialize pointers before use.",
    tags: ["pointers", "undefined"],
    answer: {
      summary: "Pointer name is uninitialized and reading it is undefined behavior.",
      keywords: ["pointer", "uninitialized", "printf"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "c-5",
    title: "Resource leak",
    language: "C",
    difficulty: "medium",
    snippet: `FILE* file = fopen(path, "r");\nif (!file) return;\nprocess(file);`,
    context: "Always fclose opened files.",
    tags: ["io", "fopen"],
    answer: {
      summary: "File opened via fopen is never closed.",
      keywords: ["fopen", "fclose", "leak"],
      line: 3,
      tolerance: 0,
      partialCreditLines: [1],
    },
  },
  {
    id: "c-6",
    title: "Format string bug",
    language: "C",
    difficulty: "hard",
    snippet: `void log_input(char* msg) {\n    printf(msg);\n}`,
    context: "Protect printf from arbitrary format strings.",
    tags: ["printf", "security"],
    answer: {
      summary: "User-controlled msg used as format string leading to format string vulnerability.",
      keywords: ["printf", "format", "vulnerability"],
      line: 2,
      tolerance: 0,
    },
  },
  {
    id: "c-7",
    title: "Integer division truncation",
    language: "C",
    difficulty: "easy",
    snippet: `int percent = count / total * 100;`,
    context: "Guard against integer truncation before multiplication.",
    tags: ["math", "division"],
    answer: {
      summary: "Division occurs before multiplication causing truncated percentage.",
      keywords: ["division", "truncation", "percent"],
      line: 1,
      tolerance: 0,
    },
  },
  {
    id: "c-8",
    title: "Missing braces",
    language: "C",
    difficulty: "medium",
    snippet: `if (flag)\n    do_work();\n    reset();`,
    context: "Recognize indentation hiding missing braces.",
    tags: ["control flow", "braces"],
    answer: {
      summary: "reset() executes regardless of flag due to missing braces.",
      keywords: ["braces", "if", "scope"],
      line: 3,
      tolerance: 0,
      partialCreditLines: [2],
    },
  },
  {
    id: "c-9",
    title: "Use-after-free",
    language: "C",
    difficulty: "hard",
    snippet: `char* data = malloc(128);\nfree(data);\nprintf("%s\n", data);`,
    context: "Do not read memory after freeing it.",
    tags: ["memory", "use-after-free"],
    answer: {
      summary: "Pointer data is freed then used in printf leading to use-after-free.",
      keywords: ["free", "use", "undefined"],
      line: 3,
      tolerance: 0,
    },
  },
  {
    id: "c-10",
    title: "Missing return",
    language: "C",
    difficulty: "medium",
    snippet: `int compute(int value) {\n    if (value > 0) {\n        return value;\n    }\n}`,
    context: "Ensure all control paths return a value.",
    tags: ["return", "control flow"],
    answer: {
      summary: "Function lacks return for value <= 0 leading to undefined behavior.",
      keywords: ["return", "undefined", "branch"],
      line: 5,
      tolerance: 0,
      partialCreditLines: [2],
    },
  },
];

export const SEED_SUBMISSIONS_ROUND1: SubmissionRound1[] = [];

const SEED_ROUND2_PROMPTS_TS_SAMPLE = SEED_ROUND2_PROMPTS.filter((prompt) => prompt.language === "TypeScript").slice(0, 10);

export const SEED_SUBMISSIONS_ROUND2: SubmissionRound2[] = [];

export const SEED_ROUND3_DUELS: Round3Duel[] = [];

export const SEED_ROUND3_SUBMISSIONS: Round3Submission[] = [];

export const SEED_MISSION_TASKS: MissionTask[] = [];

export const SEED_ROUND3_QUESTIONS: Round3Question[] = [
  {
    id: "r3q-1",
    title: "Secure Hash Showdown",
    prompt: "Given two strings a and b, determine if they produce the same SHA-256 hash without computing the full hash (logic puzzle).",
    expectedAnswer: "Only identical inputs produce identical SHA-256 hashes (ignoring collisions).",
    tags: ["crypto", "theory"],
    timeLimitMinutes: 10,
  },
  {
    id: "r3q-2",
    title: "Binary Fuse",
    prompt: "Given an array of integers, return true if there exists a pair with XOR equal to target.",
    expectedAnswer: "Use hash set to detect complements in O(n).",
    tags: ["bitwise", "hashing"],
    timeLimitMinutes: 8,
  },
];

export const SEED_AI_JOBS: AIJob[] = [];
